#!/usr/bin/env node
// build-lib.mjs: bake the traced logo layers into compositions/lib/btv-brand.js so every
// frame draws the O-plate (and, in the finale, the letters) from the SAME geometry the
// vectoriser produced. Re-run after tools/vectorize_logo.py.
import { readFileSync, writeFileSync } from "node:fs";
const layer = (n) => {
  const s = readFileSync(`assets/brand/bontrivo-${n}.svg`, "utf8");
  const inner = s.match(/<g id="logo-[a-z]+" fill="[^"]+">([\s\S]*?)<\/g>\s*<\/svg>/)[1].trim();
  return inner.replace(/\s+/g, " ");
};
const geo = JSON.parse(readFileSync("assets/brand/ring-geometry.json", "utf8"));
const out = `/* btv-brand.js: GENERATED by tools/build-lib.mjs from assets/brand/*.svg (traced from
   the user-supplied logo). Geometry in the source PNG's pixel grid (577x186). */
(function () {
  if (window.BTV_BRAND) return;
  window.BTV_BRAND = {
    ring: ${JSON.stringify(layer("ring"))},
    bean: ${JSON.stringify(layer("bean"))},
    letters: ${JSON.stringify(layer("letters"))},
    geo: ${JSON.stringify(geo)},
    // A square viewBox centred on the fitted ring centre, 1.01 x the outer radius, so a
    // plate element of size S has the ring's centre at its own centre.
    oBox: ${JSON.stringify([geo.cx - geo.r_out * 1.01, geo.cy - geo.r_out * 1.01, geo.r_out * 2.02, geo.r_out * 2.02].map((v) => +v.toFixed(3)))},
    colors: { ring: "#E65F3C", bean: "#B7CF4A", letters: "#242220" },
  };
})();
`;
writeFileSync("compositions/lib/btv-brand.js", out);
console.log("wrote compositions/lib/btv-brand.js", (out.length / 1024).toFixed(1) + " KB");
